### PR TITLE
[tuf] Fixing unknown TUF target fallback

### PR DESCRIPTION
**Pull request by truthbk**
Tentative fix: fallback to other indices if we have a TUF `UknownTargetError`

It's definitely possible that this approach might vulnerate some of the security TUF is meant to bring to the table. The main goal of this PR if this is not acceptable is to illustrate the need to be able to run something like:
```
pip -vvv install <somepackage> --index-url https://integrations-core-wheels.s3.amazonaws.com/targets/simple/ --extra-index-url https://pypi.org/simple --disable-pip-version-check
```
Such that the wheels available in the TUF repo are installed, but _ALSO_ the existing dependencies defined in <somepackage>. 

The approach followed in this PR "works", but will/may(?) resort to pulling the deps with no additional checks (unsure) like the hashes defined in the `requirements.txt` for the `integrations-core` wheels.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
I thought about this, and I recommend a two-step approach that should be less error-prone. Let me explain what I mean.

1. Use `pipette` (pip + tuf-in-toto), configuring it to use tuf-in-toto for certain URL prefixes, but not others, like so:

```bash
$ TUF_CONFIG_FILE=public-tuf-config.json pip -vvv download datadog-checks-base --index-url https://integrations-core-wheels.s3.amazonaws.com/targets/simple/ --disable-pip-version-check --no-deps --only-binary :all:
```

2. If the download is successful, then tuf-in-toto has performed security checks, and the wheel is most likely good to install. Unzip the wheel, and extract `requirements.txt`.

3. Use the following command to use `pipette` again, but without `tuf-in-toto` this time, to install third-party packages in `requirements.txt` (which should have pinned hashes for all of them) from PyPI, like so:

```bash
$  for REQ in requirements.txt; do pip -vvv download $REQ --disable-pip-version-check --require-hashes; done
```

This way, there is a clearer separation of duties between the two different tasks, and less chances of misconfiguring things. Does this make sense? Happy to answer questions, please let me know!

**Comment by trishankatdatadog** [comment]
Hi guys, does my previous comment make sense? Please let me know, thanks!

**Comment by truthbk** [comment]
@trishankatdatadog I was afraid you were going to say that. I knew your goal ultimately was to achieve something along those lines. I guess we can look into doing this with the tooling... but quite frankly that doesn't feel like a sane way to deal with pip dependencies. You're basically assuming the user has in-depth knowledge about tuf+in-toto internals.... 

A user should be able to `pip install dd-foo` and forget. If we need the logic above, then `pip` should do it transparently if you ask me.

**Comment by masci** [comment]
@trishankatdatadog I'm afraid this is a no-go for me. Being able to transparently `pip install` a check was a hard requirement since the beginning.

**Comment by trishankatdatadog** [comment]
@truthbk @masci I'm afraid there's some misunderstanding, so let me try to clarify.

So we're using an untrusted pipeline in the sense that if this pipeline is compromised, then malicious wheels could be accidentally distributed. In order to solve this problem, we are using tuf-in-toto to provide end-to-end integrity, so that users will not install anything that have not ultimately been signed by the agent integration developers themselves. The details are out of the scope of this discussion.

However, there is still some gaps left if we are not careful. If we use a one-step `pip` workflow as follows:

`$ TUF_CONFIG_FILE=public-tuf-config.json pip download datadog-checks-base --extra-index-url https://integrations-core-wheels.s3.amazonaws.com/targets/simple/`

Then there are one of two security risks:

1. `pip` would probably look at the main index first (PyPI.org), and if someone other than DataDog has registered a package with the same name, then that package would be installed, instead of the one from DataDog in the extra index.

2. Also, if the build pipeline has been compromised, then attackers could specify malicious dependencies in the wheel [metadata](https://www.python.org/dev/peps/pep-0426/#semantic-dependencies). So, if we are not careful, and install the dependencies for a wheel without question, then a compromised pipeline could tamper with these unsigned dependencies. That is why I strongly recommend a two-step `pip` workflow as in my [previous comment](https://github.com/DataDog/pip/pull/1#issuecomment-389920059), where the dependencies are specified and signed directly by developers.

This two-step `pip` workflow really should not affect the user. As we had discussed and agreed previously, the user should be using the agent to install Datadog wheels, instead of directly using `pip`. The agent can use `pip` underneath however it likes, including the recommended workflow above, which should not be too difficult to program.

I am also copying a security expert, @JustinCappos, to get his thoughts on the subject. I may be overestimating the security risks, and it would be good to get an independent opinion.

**Comment by truthbk** [comment]
Also, let me showcase a potential problematic scenario with the manual process:

Say we have an integration `datadog-foo`, this integration may depend on `datadog-prometheus`, `datadog-python`, and other third party integrations. The currently proposed workflow: 
1. `datadog-agent custompip install datadog-foo`
2. tooling downloads `custompip` from TUF
3. tooling unzips in temporary (or not) location
4. tooling installs requirements.txt bundled with wheel
5. if necessary (not sure if we need to use a temporary location) move unzipped wheel to it’s final location

In this scenario the intermediate step  `pip install -r datadog-foo-requirements.txt` (4) isn't even a fail-safe call because the requirements file would contain both TUF and PyPI dependencies. On top of that, we can't even say it's safe to assume `datadog-` is a prefix good enough to decide if we should go to the TUF index either, because `datadog-python` is actually only in `pypi`.

To address that we might need to enter a spiral of recursive calls to the tool by the tool (`custompip`) which is anything but desirable.

**Comment by truthbk** [comment]
NOTE: I had been expecting PyPi to be the secondary index, and the TUF repo to be the main one.
```
TUF_CONFIG_FILE=public-tuf-config.json pip install datadog-checks-base --index-url https://tuf-repo.foo.com/targets/simple/ --extra-index-url https://pypi.org/simple/
```  
I believe in the scenario above all dependencies in the dependency tree are first searched for in the TUF'ened repo, falling back to PyPi only if the dependencies are not found there.

**Comment by trishankatdatadog** [comment]
@truthbk Ah, thanks, now I understand your concerns much better. Thanks for raising it, it's a very good one, and I want to make sure we address your concerns in a mutually satisfactory manner :) 

Regarding your proposed way to configure pip to prioritize the DataDog index before the PyPI index: I believe it should work. I will verify by reading the source code, and we should also do some tests.

Regarding mixing Datadog and 3rd-party dependencies (whether in the more trustworthy `requirements.txt`, or in the less trustworthy wheel metadata record), this is a use case that had not occurred to me before. I think as long as we always prioritize the DataDog index before the PyPI index, then this should solve this issue too, but let me think about this, please.

I just want to make sure there are no accidental security slips no matter what we do, and I hope you understand.

**Comment by trishankatdatadog** [comment]
Following our meeting earlier today, we have decided that third party dependencies are a known risk. Two ways of mitigating this risk are:

1. Using the [TUF configuration file](https://github.com/DataDog/pippi/blob/fc8dbc97877fbc9110afce0ffb8894e89a679d11/public-tuf-config.json) in [pip+TUF](https://github.com/pypa/pip/compare/10.0.1...DataDog:trishankatdatadog/10.0.1.tuf) to intercept all `datadog-*` package requests, and ensure they are downloaded and verified from the DataDog TUF repository.

2. Use the suggested [two-step workflow](https://github.com/DataDog/pip/pull/1#issuecomment-389920059) to ensure that we download and install / update only 3rd party dependencies with hashes that have been specified / pinned (and possibly signed) by our developers.

We can discuss the second step at a later date. I hope this is satisfactory. Let's discuss more offline, and thanks for your understanding!

**Pull request closed without merging**
